---
development:
  dialect: "sqlite3"
  database: ./unictelezioni_dev.sqlite

test:
  dialect: "sqlite3"
  database: ./unictelezioni_test.sqlite

production:
  dialect: "sqlite3"
  database: ./unictelezioni_production.sqlite
